---
apiVersion: v1
kind: Service
metadata:
  name: envoy-${project.artifactId}
spec:
  ports:
  - name: envoy-admin
    port: 8001
    protocol: TCP
    targetPort: 8001

  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80

  selector:
    project: sb-webmvc-envoy
    provider: fabric8
    group: org.workspace7.msa
