---
apiVersion: v1
kind: Service
spec:
  ports:
  - name: ipaddress-service
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    project: spring-boot-ipaddress-service
    provider: fabric8
    group: io.fabric8.quickstarts
